version: "3.9"

   

services:
    #Banco de Dados
    db:
        image: postgres:14.5
        container_name: postgres
        restart: always
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: parking_db
        volumes:
            - ./bancoDados:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - banco
            
    
    #INTERFACE PARA ACESSO AO POSTGRESQLclear
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: xxxxxxx@gmail.com
            PGADMIN_DEFAULT_PASSWORD: xxxxxxx
        ports:
            - 8889:80
        networks:
            - banco
        depends_on:
            - db

volumes:
    bancoDados:

networks:
    banco:
  

